### ISSUE TITLE
expected form of input data

### ISSUE THREAD

**Issue by kingfish777** [bd2kccd/cytoscape-tetrad#1]
Howdy Jeremy,
How should the input look for cytoscape-tetrad? 
I tried the obvious (using relevant portion of output log from r-causal): 
pain -> medication
medication -> ade
I was zoning out or working on data conversion during that part of the workshop.
Thanks!
 -S

**Comment by espinoj** [comment]
Hi Scott,

If you install the new cytoscape-tetrad plugin from https://github.com/bd2kccd/cytoscape-tetrad/releases you will have a function in cytoscape for importing tetrad output directly.

Best,
Jeremy

**Comment by espinoj** [comment]
So does that mean that a Tetrad session need to be up and running and that
there is no preparation work that needs to be done with plain text output
from Tetrad cmd?

**Comment by espinoj** [comment]
Yes, all you need is the tetrad txt output. I think causal CMD will also
work.

**Comment by kingfish777** [comment]
I was able to make output from r-causal interoperable with cytoscape-tetrad by prepending a "Graph Edges:\n" string and retaining the numbers associated with each edge in output. Yay!
 --Scott

**Comment by kingfish777** [comment]
Hey - I have a new one: could we get the tetrad output graph loading function work from RCytoscape? 
Actually, I mean, the successor to RCytoscape, CyREST: http://apps.cytoscape.org/apps/cyrest
Now that would be really cool. 
Thanks!
Scott
