### ISSUE TITLE
Problem opening cytoscape jar

### ISSUE THREAD

**Issue by rubencmu** [bd2kccd/cytoscape-tetrad#2]
Hi, I am unable to launch the jar file for the Cytoscape plugin

macOS Sierra, 10.12.2
Java 8 update 131

**Comment by espinoj** [comment]
The cytoscape plugin needs to be installed from within cytoscape.

In cytoscape select apps->install from file...

Have you tried this?

**Comment by rubencmu** [comment]
Thanks @espinoj ,  that worked.
