### ISSUE TITLE
can't read a file in

### ISSUE THREAD

**Issue by harryhoch** [bd2kccd/cytoscape-tetrad#5]
try to read a file (attached) and get no indication that anything has happened. 
[fgsc_Retention.txt_1519855666373.json.txt](https://github.com/bd2kccd/cytoscape-tetrad/files/1769054/fgsc_Retention.txt_1519855666373.json.txt)

**Comment by yuanzhou** [comment]
I got this fixed and now you should be able to load this tetrad JSON into the Cytoscape via this app. Please uninstall the old one and build the new jar from development branch then install this app to Cytoscape.

When generating this graph JSON, if no bootstraping is applied, you won't see the edge type probabilities in Cytoscape though. Maybe @marksilvis's annotation app allows users to add new ones.
